---
title: "D2SC ICMAs"
author: "Rebecca Blum"
output: html_notebook
---
``` {r} 
#| label: setup 
#| include: false

library("tidyverse")
library("palmerpenguins")
library("nycflights13")
```

## ICMA September 3 2026

```{r}
# here I'm plotting data from cars 
plot(cars)
```
 # I see that in the plot as speed goes up so does distance 
 
## ICMA 9-10-26
 
```{r}
 ggplot(data=penguins, mapping = aes(x= flipper_length_mm, 
                                    y= bill_length_mm))+ geom_point()

```

```{r}
PlantGrowth
ggplot(data=PlantGrowth, mapping=aes(y=weight, x=group)) + geom_point(alpha=0.5) + stat_summary(geom = "pointrange", fun.data = "mean_se",color="purple")

```
This is tidy data! 

## ICMA 9-15-2026

```{r}
  PlantGrowth |> 
  ggplot(aes(y=weight, x = group)) +  
  geom_boxplot(width = 0.2)
``` 
```{r} 
glimpse(flights)
flights |> 
  filter(month == 1 & day == 1)
  flights |> 
    arrange(desc(month))
  flights |> 
      distinct(origin,dest)
```
```{r}
flights |> 
    filter (arr_delay > 120 & dep_delay >= 0) |> arrange(desc(arr_delay)) |> 
    arrange(dep_delay)
```      

```{r}
  flights <- nycflights13 :: flights 
    glimpse (flights)
# You see a snapshot of the flight data set, its in column form 
```
```{r}
flights |> 
  # distance is miles, time is minutes 
  # convert to miles/ hour using *60 
  mutate(speed = distance/air_time * 60, .before = 1) |> head() |> 
    select(year, month, day, dep_time, air_time, distance, speed) 
```
```{r}
flights |> 
  group_by(month) |> 
  summarise(avg_delay = mean(dep_delay, na.rm = TRUE)) |> round(2)
```
## ICMA 9-17-2026
```{r}
flights |> 
  group_by(month) |> 
  slice_max(dep_delay, n = 2)
```
```{r}
flights |> 
group_by(month)|> summarise(mean_delay = mean (arr_delay, na.rm =TRUE),
                            sd_delay = sd(arr_delay, na.rm = TRUE),  
                            number_late = sum(arr_delay > 0, na.rm = TRUE), 
                            total_number = n()) |> 
                  mutate(percentage = number_late/total_number) |> round(2) |> 
                  ggplot(aes(y = percentage, x = month )) + 
                  geom_line() + 
                  scale_x_continuous(breaks = 1:12) + 
                  ylim(0,0.55)
```